<div class="leaderboard-container">
    <h2><?= $game['name'] ?></h2>
    <table>
        <thead>
            <tr>
                <th>Rank</th>
                <th>Position</th>
                <th>Nom du joueur</th>
                <th>Score</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach( $users as $index=>$user ) : ?>
                <?php if( $user['score_value'] != 0 ): ?>
                    <tr class="leaderboard-place">
                        
                    <?php switch( $index ):
                        case 0: ?>
                        <td><?= $grandMaster ?></td>
                    <?php break; ?>
                    
                        <?php case 1: ?>
                        <td><?= $master ?></td>
                    <?php break; ?>
                    
                        <?php case 2: ?>
                        <td><?= $miniMaster ?></td>
                    <?php break; ?>
                    
                    <!-- De la 4ème place jusqu'à la 6ème place. -->
                    <?php case ( $index >= 3 && $index <= 5): ?>
                        <td><?= $diamant ?></td>
                    <?php break; ?>
                    
                    <?php case ( $index >= 6 && $index <= 9): ?>
                        <td><?= $emeraude ?></td>
                    <?php break; ?>
                    
                    <?php case ( $index >= 10 && $index <= 14): ?>
                        <td><?= $platine ?></td>
                    <?php break; ?>
                    
                    <?php case ( $index >= 15 && $index <= 19): ?>
                        <td><?= $or ?></td>
                    <?php break; ?>
                    
                    <?php case ( $index >= 20 && $index <= 24): ?>
                        <td><?= $argent ?></td>
                    <?php break; ?>
                    
                    <?php case ( $index >= 25 && $index <= 29): ?>
                        <td><?= $bronze ?></td>
                    <?php break; ?>
                    
                    <?php case ( $index >= 30 ): ?>
                        <td><?= $pierre ?></td>
                    <?php break; ?>
                    <?php endswitch; ?>
                        <td>#<?= $index + 1 ?></td>
                        <td><?= $user['username'] ?></td>
                        <td><?= $user['score_value'] ?></td>
                        <td><a href="index.php?route=userProfile&id=<?= $user['user_id'] ?>"><i class="fa-solid fa-user"></i></a></td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>