<h1>MODIFIER UN JEU</h1>
<form action="index.php?route=editGame&id=<?= $game['id'] ?>" method="POST" class="admin-game-form">
        <div class="inputs">
                <label for="name">Nom</label>
                <input type="text" name="name" value="<?= $game['name'] ?>"/>
        </div>
        
        <div class="inputs">
                <label for="description">Description</label>
                <textarea rows="5" cols="25" name="description"><?= $game['description'] ?></textarea>
        </div>
        
        <div class="inputs">
                <label for="description">Slogan</label>
                <textarea rows="3" cols="15" name="slogan"><?= $game['slogan'] ?></textarea>
        </div>
        
        <div class="inputs">
                <label for="submit"></label>
                <input type="submit" value="Confirmer" name="submit" class="more"/>
        </div>
</form>